### PR TITLE
V3.10 Add support for Windows 10 UWP and Windows 8.1 Universal Apps

### PR DESCRIPTION
**Pull request by stammen**
This PR adds the project files for building the samples for Windows 10 UWP and Windows 8.1 Universal  apps.

### CODE REVIEW

**Comment by slackmoehrle** [comment]
@stammen Thanks. I will bring this down in the next few days locally and test it. I have other changes to do for the samples as well. We really appreciate the effort. Thank you.

**Comment by stammen** [comment]
@slackmoehrle Why was this never pulled?

**Comment by slackmoehrle** [comment]
@stammen I haven't made it to it yet. I'll make time for this. I apologize.

**Comment by stammen** [comment]
Thanks for the update

**Pull request merged**
